---
title: "graphs_properties_analysis"
output: html_document
date: "2023-02-25"
---

```{r}
install.packages("gridExtra")
```

```{r}
library(dplyr)
library(ggplot2)
library(GGally)
library(viridis)
library(gridExtra)
# library(tidyverse)

```

```{r}
mean_tr = c("../correlations/training/dimensionality_reduction_1/10_10_10/synolitic_method_1/features/perception/mean.txt",
                 "../correlations/training/dimensionality_reduction_1/10_10_10/synolitic_method_1/features/imagery/mean.txt")
median_tr = c("../correlations/training/dimensionality_reduction_1/10_10_10/synolitic_method_1/features/perception/median.txt",
                   "../correlations/training/dimensionality_reduction_1/10_10_10/synolitic_method_1/features/imagery/median.txt")
max_min_distance_tr = c("../correlations/training/dimensionality_reduction_1/10_10_10/synolitic_method_1/features/perception/max_min_distance.txt",
                             "../correlations/training/dimensionality_reduction_1/10_10_10/synolitic_method_1/features/imagery/max_min_distance.txt")
quantiles_distance_tr = c("../correlations/training/dimensionality_reduction_1/10_10_10/synolitic_method_1/features/perception/quantiles_distance.txt",
                               "../correlations/training/dimensionality_reduction_1/10_10_10/synolitic_method_1/features/imagery/quantiles_distance.txt")
max_tr = c("../correlations/training/dimensionality_reduction_1/10_10_10/synolitic_method_1/features/perception/max.txt",
                "../correlations/training/dimensionality_reduction_1/10_10_10/synolitic_method_1/features/imagery/max.txt")
min_tr = c("../correlations/training/dimensionality_reduction_1/10_10_10/synolitic_method_1/features/perception/min.txt",
                "../correlations/training/dimensionality_reduction_1/10_10_10/synolitic_method_1/features/imagery/min.txt")
quantile_1_tr = c("../correlations/training/dimensionality_reduction_1/10_10_10/synolitic_method_1/features/perception/quantile_1.txt",
                       "../correlations/training/dimensionality_reduction_1/10_10_10/synolitic_method_1/features/imagery/quantile_1.txt")
quantile_2_tr = c("../correlations/training/dimensionality_reduction_1/10_10_10/synolitic_method_1/features/perception/quantile_2.txt",
                       "../correlations/training/dimensionality_reduction_1/10_10_10/synolitic_method_1/features/imagery/quantile_2.txt")

mean_test = c("../correlations/test/dimensionality_reduction_1/10_10_10/synolitic_method_1/features/perception/mean.txt",
                 "../correlations/test/dimensionality_reduction_1/10_10_10/synolitic_method_1/features/imagery/mean.txt")
median_test = c("../correlations/test/dimensionality_reduction_1/10_10_10/synolitic_method_1/features/perception/median.txt",
                   "../correlations/test/dimensionality_reduction_1/10_10_10/synolitic_method_1/features/imagery/median.txt")
max_min_distance_test = c("../correlations/test/dimensionality_reduction_1/10_10_10/synolitic_method_1/features/perception/max_min_distance.txt",
                             "../correlations/test/dimensionality_reduction_1/10_10_10/synolitic_method_1/features/imagery/max_min_distance.txt")
quantiles_distance_test = c("../correlations/test/dimensionality_reduction_1/10_10_10/synolitic_method_1/features/perception/quantiles_distance.txt",
                               "../correlations/test/dimensionality_reduction_1/10_10_10/synolitic_method_1/features/imagery/quantiles_distance.txt")
max_test = c("../correlations/test/dimensionality_reduction_1/10_10_10/synolitic_method_1/features/perception/max.txt",
                "../correlations/test/dimensionality_reduction_1/10_10_10/synolitic_method_1/features/imagery/max.txt")
min_test = c("../correlations/test/dimensionality_reduction_1/10_10_10/synolitic_method_1/features/perception/min.txt",
                "../correlations/test/dimensionality_reduction_1/10_10_10/synolitic_method_1/features/imagery/min.txt")
quantile_1_test = c("../correlations/test/dimensionality_reduction_1/10_10_10/synolitic_method_1/features/perception/quantile_1.txt",
                       "../correlations/test/dimensionality_reduction_1/10_10_10/synolitic_method_1/features/imagery/quantile_1.txt")
quantile_2_test = c("../correlations/test/dimensionality_reduction_1/10_10_10/synolitic_method_1/features/perception/quantile_2.txt",
                       "../correlations/test/dimensionality_reduction_1/10_10_10/synolitic_method_1/features/imagery/quantile_2.txt")
```

```{r}
data_tr_per <- read.csv(file=mean_tr[1], sep=",")
colnames(data_tr_per)
```

```{r}
plot.1 <- function(tr, test) {
  data_tr_per <- read.csv(file=tr[1], sep=",")
  data_tr_im <- read.csv(file=tr[2], sep=",")
  data_test_per <- read.csv(file=test[1], sep=",")
  data_test_im <- read.csv(file=test[2], sep=",")
  
  data_per = rbind(data_tr_per, data_test_per) %>% mutate(mode = "seen")
  data_im = rbind(data_tr_im, data_test_im) %>% mutate(mode = "imagined")
  
  data = rbind(data_per, data_im)
  
  data %>%
  ggpairs(diag=list(continuous = wrap("barDiag", alpha=0.7)), 
          upper=list(continuous = wrap("blank", alpha=0.7)),
          lower=list(continuous = wrap("points", alpha=0.7)),
          aes(colour=mode), legend=1, columns = c("mean", "quantile_2", "std"), 
          columnLabels=c("mean of edge weights","quantile(0.9) of edge weights","std of edge weights")
          )
}
```


```{r, message=FALSE, warning=FALSE}
plot.1(mean_tr, mean_test)
# plot.1(min_tr, min_test)
# plot.1(quantiles_distance_tr, quantiles_distance_test)
```

```{r}
plot.2 <- function(tr, test) {
  data_tr_per <- read.csv(file=tr[1], sep=",")
  data_tr_im <- read.csv(file=tr[2], sep=",")
  data_test_per <- read.csv(file=test[1], sep=",")
  data_test_im <- read.csv(file=test[2], sep=",")
  
  data_per = rbind(data_tr_per, data_test_per) %>% mutate(mode = "seen")
  data_im = rbind(data_tr_im, data_test_im) %>% mutate(mode = "imagined")
  
  data = rbind(data_per, data_im)
  
p1 <- data %>%
        ggplot(aes(x=mode, y=mean, fill=mode)) +
        geom_boxplot(outlier.shape = NA, alpha=0.7) + 
        geom_jitter(color="black", size=0.4, alpha=0.9) + 
        theme(legend.position = "none") +
        ylab("mean of edge weights")
p2 <- data %>%
        ggplot(aes(x=mode, y=quantile_2, fill=mode)) +
        geom_boxplot(outlier.shape = NA, alpha=0.7) + 
        geom_jitter(color="black", size=0.4, alpha=0.9) + 
        theme(legend.position = "none") +
        ylab("quantile(0.9) of edge weights")
p3 <- data %>%
        ggplot(aes(x=mode, y=std, fill=mode)) +
        geom_boxplot(outlier.shape = NA, alpha=0.7) + 
        geom_jitter(color="black", size=0.4, alpha=0.9) + 
        theme(legend.position = "none") +
        ylab("std of edge weights")
grid.arrange(p1, p2, p3, ncol = 3, nrow = 1)
}
```


```{r}
plot.2(mean_tr, mean_test)
```





